### ISSUE TITLE
Eggdrop 1.8.0

### ISSUE THREAD

**Issue by sacredland** [florian-sander/gseen.mod#6]
When loading the eggdrop, 1.8: 
 Can't load modules gseen: This module requires eggdrop1.4.0 or later

1.8 is later then 1.4...but wont load the module

**Comment by florian-sander** [comment]
Which version did you use? The one available on kreativrauschen.com (1.1.1 dev3) will not work with eggdrop 1.8. If you used that one, please download the current source from GitHub and try again.

Also please report if the one from GitHub works. I did not have a chance to test it myself, yet. :) If it can be confirmed that it is working, I can release it to avoid future confusion.

**Comment by sacredland** [comment]
it work pretty well

**Comment by sacredland** [comment]
This version work pretty well. You should refer your old website here, as it is listed into the eggdrop.conf

**Comment by florian-sander** [comment]
Thanks a lot for testing and confirming! I have released a new version (the first one in over a decade! ^_^) and updated the website.
